#!/bin/sh
git submodule update --init --recursive
# TODO: wrap below in conditional if pulled from origin/upstream main remote branch
pushd .
PROJECT_ROOT=$(git rev-parse --show-toplevel)
cd "$PROJECT_ROOT"
rm -rf build
mkdir build
cd build
cmake ..
make
popd
